export type PredictSide = 'Yes' | 'No';
export type PairConfig = {
  name: string;
  predictMarketId: string;
  predictSide?: PredictSide;
  polymarketConditionId?: string;
  polymarketOutcome?: string;
  polymarketTokenId?: string;
  outcome?: PredictSide;
  polymarketYesTokenId?: string;
  polymarketNoTokenId?: string;
  threshold?: number;
  minSize?: number;
  feeBuffer?: number;
};
export type BookLevel = {
  price: number;
  size: number;
};
export type TopBook = {
  bid: BookLevel | null;
  ask: BookLevel | null;
  bidDepth: number;
  askDepth: number;
};
export type SpreadDirection = 'BUY_PREDICT_SELL_POLY' | 'BUY_POLY_SELL_PREDICT';
export type SpreadResult = {
  pair: PairConfig;
  checkedAt: string;
  ok: boolean;
  error?: string;
  predictBook?: TopBook;
  polyBook?: TopBook;
  direction?: SpreadDirection;
  directionLabel?: string;
  buyVenue?: 'Predict.fun' | 'Polymarket';
  sellVenue?: 'Predict.fun' | 'Polymarket';
  buyPrice?: number;
  sellPrice?: number;
  gap?: number;
  gapCents?: number;
  comparableSize?: number;
  threshold: number;
  minSize: number;
  feeBuffer: number;
  alert: boolean;
};
export type ResolveResult = {
  predictMarketId: string;
  predictTitle: string;
  polymarketConditionId: string;
  tokenCount: number;
  tokens: Array<{ outcome: string; tokenId: string }>;
  pairs: PairConfig[];
  mappingNote: string;
};
export type PredictMarketSummary = {
  id: string;
  title: string;
  question?: string;
  slug?: string;
  categorySlug?: string;
  status?: string;
  tradingStatus?: string;
  isResolved?: boolean;
  closed?: boolean;
  active?: boolean;
  category?: string;
  endDate?: string;
  endMs?: number | null;
  volume?: number;
  liquidity?: number;
  yesPrice?: number | null;
  noPrice?: number | null;
  hourlyRate: number;
  hourlyRateSource?: 'current' | 'schedule' | 'recursive' | 'none';
  spreadThreshold?: number;
  shareThreshold?: number;
  polymarketConditionIds: string[];
  hasPolymarket: boolean;
  tradeable: boolean;
  raw?: unknown;
};
